name: shap_xai 
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=1.5.2
  - numpy=1.23.5
  - matplotlib=3.6.2
  - pip=22.3.1
  - python=3.9
  - jupyter=1.0.0
  - scikit-learn==1.2.2
  - pip:
    - shap==0.41.0
